
[project]
name = "tiozin"
version = "0.1.0"
description = "Tiozin, your friendly ETL framework"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "pydantic ==2.12.3",
  "environs ==14.3.0",
  "single-source ==0.4.0",
  "python-json-logger ==4.0.0",
  "pendulum ==3.1.0",
  "uuid6 ==2025.0.1",
  "typer ==0.20.0",
  "ruamel-yaml ==0.18.17",
  "uuid-utils ==0.12.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
tiozin = "tiozin.cli:main"

[tool.uv]
required-version = ">=0.8.1"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[dependency-groups]
dev = [
  {include-group = "lint"},
  {include-group = "test"}
]
test = [
  "pytest-asyncio ==1.2.0",
  "pytest-cov ==7.0.0",
  "testcontainers ==4.13.2"
]
lint = [
  "flake8 ==7.3.0",
  "flake8-pyproject ==1.2.3",
  "autoflake ==2.3.1",
  "black ==25.9.0",
  "isort ==7.0.0",
  "pre-commit ==4.3.0"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--cov --cov-report term"

[tool.coverage.run]
source = ["tiozin"]
omit = [
  "tiozin/app.py",
  "tiozin/env.py",
  "tiozin/config.py",
  "tiozin/logs.py",
]

[tool.coverage.report]
fail_under = 60
show_missing = true

[tool.isort]
profile = "black"
line_length = 100
force_sort_within_sections = true
skip = [".venv"]

[tool.black]
line-length = 100
exclude = '\.venv'

[tool.flake8]
max-line-length = 100
count = true
exclude = [".venv"]

[tool.autoflake]
in-place = true
recursive = true
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-unused-variables = true
remove-duplicate-keys = true
